"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Weapon_1 = require("./Weapon");
const Spell_1 = require("./Spell");
const Warrior_1 = require("./Warrior");
const Mage_1 = require("./Mage");
const Party_1 = require("./Party");
const adaga = new Weapon_1.Weapon("Adaga", 35);
const axe = new Weapon_1.Weapon("Axe", 45);
const Snatch = new Spell_1.Spell("Snatch", 50, 30);
const infinit = new Spell_1.Spell("Ice infinit", 30, 10);
const warrior1 = new Warrior_1.Warrior("Meliodas", 10, 150, 80, adaga);
const warrior2 = new Warrior_1.Warrior("Escanor", 9, 160, 90, axe);
const mage1 = new Mage_1.Mage("Ban", 12, 150, 100, Snatch);
const mage2 = new Mage_1.Mage("Merlin", 8, 120, 120, infinit);
const party = new Party_1.Party("The Dragon Slayers");
party.addMember(warrior1);
party.addMember(warrior2);
party.addMember(mage1);
party.addMember(mage2);
party.showMembers();
warrior1.attack();
warrior2.attack();
mage1.castSpell();
mage2.castSpell();
party.removeMember(warrior2);
party.showMembers();
